default:
    autoload:
        '': '%paths.base%/../features/bootstrap'
    suites:
        default:
            paths: [ '%paths.base%/../features' ]
            contexts:
             - FeatureContext:
                    parameters:
                        server: mobile-hub.lambdatest.com
                        user: "${LT_USERNAME}"
                        key: "${LT_ACCESS_KEY}"
                        capabilities:
                            build: "behat-appium-android"
                            name: "single-behat-test"
                            isRealMobile: true
                            app: "${ANDROID_APP_ID}"
                            deviceName: Galaxy S21 Ultra 5G
                            platformName: Android
                            platformVersion: 11
                            visual: true
                            network: true
                            console: true
                            autoGrantPermissions: true
                        environments:
                            -
                                deviceName: "Galaxy S24 Ultra"
                                platform: "Android"
                                platformVersion: "14"


